apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-video-app
  namespace: crawler-apps
spec:
  replicas: 3 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: youtube-video-app
  template:
    metadata:
      labels:
        app: youtube-video-app
    spec:
      containers:
      - name: youtube-video-app
        image: mglue/youtube-video-app:1.0
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: youtube-video-app-service
spec:
  selector:
    app: youtube-video-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer # Use "LoadBalancer" or "NodePort" as per your setup
